# Generated by Django 5.0.4 on 2024-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursemeterial_name', models.CharField(max_length=45)),
                ('meterial', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='meterial/')),
            ],
        ),
    ]
