# Generated by Django 5.0.4 on 2024-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_course_batch_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Student',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Teacher',
            new_name='is_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
