# Generated by Django 5.0.4 on 2024-05-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_is_student_user_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
