# Generated by Django 5.0.4 on 2024-05-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_remove_user_is_student_remove_user_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('files', models.FileField(upload_to='course_meterial/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.teacher')),
            ],
        ),
    ]
