# Generated by Django 5.0.4 on 2024-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_coursemeterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='teacher@example.com', max_length=34),
        ),
    ]
