# Generated by Django 5.0.4 on 2024-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
