# Generated by Django 5.0.4 on 2024-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_teacher_password_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
