# Generated by Django 5.0.4 on 2024-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='importex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Exam_Name', models.CharField(max_length=150)),
                ('Date', models.CharField(max_length=250)),
                ('Points', models.FloatField()),
            ],
        ),
    ]
