# Generated by Django 5.0.4 on 2024-05-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0011_importex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importex',
            name='Points',
            field=models.CharField(max_length=45),
        ),
    ]
