# Generated by Django 5.0.4 on 2024-05-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0017_alter_importex_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importex',
            old_name='Points',
            new_name='Point',
        ),
    ]
