# Generated by Django 5.0.4 on 2024-05-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0018_rename_points_importex_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('Grade', models.CharField(choices=[('S', 'S'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('F', 'F')], max_length=15)),
                ('class_perfomance', models.CharField(choices=[('outstanding', 'OutStanding'), ('veryGood', 'VeryGood'), ('good', 'Good'), ('average', 'Average'), ('bad', 'Bad'), ('veryBad', 'VeryBad')], max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student')),
            ],
        ),
    ]
