# Generated by Django 5.0.4 on 2024-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0019_achivments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivments',
            name='class_perfomance',
            field=models.CharField(choices=[('outstanding', 'outstanding'), ('veryGood', 'veryGood'), ('good', 'good'), ('average', 'average'), ('bad', 'bad'), ('veryBad', 'veryBad')], max_length=20),
        ),
    ]
