# Generated by Django 5.0.4 on 2024-05-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0020_alter_achivments_class_perfomance'),
    ]

    operations = [
        migrations.CreateModel(
            name='attandence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.teacher')),
            ],
        ),
    ]
