# Generated by Django 5.0.4 on 2024-06-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0020_alter_achivments_class_perfomance'),
    ]

    operations = [
        migrations.CreateModel(
            name='attandence1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('arrival_time', models.TimeField()),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.teacher')),
            ],
        ),
    ]
