# Generated by Django 5.0.4 on 2024-06-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0021_attandence1'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageuploder1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=125)),
                ('imagefile', models.ImageField(blank=True, default='img.jpg', null=True, upload_to='image/')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student')),
            ],
        ),
    ]
