# Generated by Django 5.0.4 on 2024-06-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0022_imageuploder1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploder1',
            name='imagefile',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='image/'),
        ),
    ]
